package shop.mtcoding.blog._core.utils;

public enum JwtEnum {
    ACCESS_TOKEN_NOT_FOUND,
    ACCESS_TOKEN_INVALID,
    ACCESS_TOKEN_TIMEOUT,
    ACCESS_TOKEN_ROLE_ERROR,
    REFRESH_TOKEN_NOT_FOUND,
    REFRESH_TOKEN_INVALID,
    REFRESH_TOKEN_TIMEOUT,
    ACCESS_TOKEN_DONT_SAVED_REDIS,
    REFRESH_TOKEN_NOT_MATCH_SAVED_REDIS;
}
